HELP_PID = "Specifies particular PIDs to check for suspiciousness."
HELP_MITRE_ATTACK = "Adds corresponding TTPs STIX objects to final output, if there any."
HELP_SUS_TRSH = "Specifes thershold value in range <0-100> of suspiciousness, processess with value of suspiciousness below that value wouldn't be displayed."
HELP_OUT_FORMAT = "Specifies format of output."
HELP_NET_DETAILED = "Shows detailed information about each IP address the examined process had connection with."
